### ISSUE TITLE
plot_drivers on continuous variables

### ISSUE THREAD

**Issue by komalsrathi** [dswatson/bioplotr#3]
Using plot_drivers.R to see how gene expression is affected by some of my covariates.
I have 48 samples and 10 covariates - all continuous variables:

```
# class of all covariates
# A tibble: 10 x 2
   Feature            Class  
   <chr>              <chr>  
 1 VO2max             numeric
 2 running.time       numeric
 3 VO2.end.max        numeric
 4 VO2.avg.CLAMS      numeric
 5 RER.avg.CLAMS      numeric
 6 activity.CLAMS     numeric
 7 weight             numeric
 8 respiration.oxphos numeric
 9 delta.VO2max       numeric
10 delta.running.time numeric
```

Applying function on VO2max as the blocking variable gives the following error

```
plot_drivers(dat = voomData, clin = covariates, block = "VO2max", unblock = "running.time", p_adj = "BH")
# A tibble: 10 x 2
   Feature            Class    
   <chr>              <chr>    
 1 VO2max             character
 2 running.time       numeric  
 3 VO2.end.max        numeric  
 4 VO2.avg.CLAMS      numeric  
 5 RER.avg.CLAMS      numeric  
 6 activity.CLAMS     numeric  
 7 weight             numeric  
 8 respiration.oxphos numeric  
 9 delta.VO2max       numeric  
10 delta.running.time numeric 
 
Error in terms.formula(formula, data = data) : 
  'data' argument is of the wrong type
```

**Comment by dswatson** [comment]
Thanks for using the package! Still very much in beta (clearly!) haha. Do you have a reproducible example for this? What's the class of your clinical data file?

**Comment by komalsrathi** [comment]
Thanks for the quick response. The clinical file is of type `data.frame`:

```
> class(covariates)
[1] "data.frame"
```

I have attached the input: voomData (voom normalized expression matrix) and covariates (clinical file containing all covariates):
[example.RData.zip](https://github.com/dswatson/bioplotr/files/4656774/example.RData.zip)

**Another related question**: All my covariates are numeric/continuous variables but I see that the function is converting the blocking variable (in this case `VO2max`) to character. Can you please tell me why is that? 

Thanks
Komal

**Comment by dswatson** [comment]
The issue is that the `block` argument is only for categorical variables, and `plot_drivers` will internally convert the feature to `character` if it isn't already. The original goal here was to adjust for repeated measures, e.g. if you have multiple samples from the same patient. 

It appears your `VO2max` variable is continuous, however. Was your intention to adjust for this feature in all association tests? If so, you may want to regress out the effects prior to visualization. Assuming your (filtered and normalized) count matrix is `y`, you could try something like:

```r
# Fit model
des <- model.matrix(~ VO2max, data = covariates)
v <- voom(y, des)
fit <- eBayes(lmFit(v, des))

# Remove VO2max signal
beta <- fit$coefficients[, 2]
new_y <- v$E - beta %*% t(des[, 2])
```
And then proceed with `new_y` and `block = NULL`. I'm not sure what "unblocking" on `running.time` would amount to in this context, though? Depends what you were hoping to do with that argument.

Hope this helps!

**Comment by komalsrathi** [comment]
Hi David,

The goal was to find if the sample variable VO2max has an effect on gene expression or not. Maybe this is not the correct package for that? Initially I was just going to do a linear regression of expression vs VO2max to see which genes are correlated with VO2max. Maybe I should stick to that?

Thanks
Komal

**Comment by dswatson** [comment]
Sounds like you probably want a `limma::voom` analysis. Check the package [documentation](https://www.bioconductor.org/packages/devel/bioc/vignettes/limma/inst/doc/usersguide.pdf) for more details.
