### ISSUE TITLE
How to intrepret results

### ISSUE THREAD

**Issue by lukais-i0han** [dswatson/bioplotr#7]
Hi,

I used the _plot_drivers() function to know how 3 variables may be affecting my data and I got the following result: 
![example](https://user-images.githubusercontent.com/64033448/136564576-b96754bf-e5ee-4990-8a38-70101704ddb2.png)

I want to know how to interpret the image above.
Thanks in advance.

**Comment by dswatson** [comment]
The colors represent the strength of the association. The dark red tile suggests that RIN is a major driver of omic variation, since it's highly correlated with the first PC (which captures over 25% of the variation in your data). Read the package documentation for more details on association tests, multiple testing correction, etc.

**Comment by lukais-i0han** [comment]
Thanks for your answer!!!!
